# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.2.6
_src_path: https://github.com/jupyterlab/extension-template
author_email: anastasiia.sliusar@quantstack.net
author_name: Anastasiia Sliusar
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: my_first_extension
mimetype: ''
mimetype_name: ''
project_short_description: A JupyterLab extension according to a tutorial
python_name: my_first_extension
repository: https://github.com/AnastasiaSliusar/quantstack-jupyter-lab-ext-tutorial
test: true
viewer_name: ''

